-- 1. How many unique nodes are there on the Data Bank system?

SELECT 
    count(distinct NODE_ID) AS UNIQUE_NODES
FROM REGIONS AS RE
JOIN CUSTOMER_NODES AS CN ON RE.REGION_ID = CN.REGION_ID
JOIN CUSTOMER_TRANSACTIONS AS CT ON CN.CUSTOMER_ID = CT.CUSTOMER_ID;

-- 2. What is the number of nodes per region?

SELECT 
    REGION_NAME,
    COUNT(NODE_ID) AS NUMBER_OF_NODES
FROM REGIONS AS RE
JOIN CUSTOMER_NODES AS CN ON RE.REGION_ID = CN.REGION_ID
JOIN CUSTOMER_TRANSACTIONS AS CT ON CN.CUSTOMER_ID = CT.CUSTOMER_ID
GROUP BY REGION_NAME;

-- 3. How many customers are allocated to each region?

SELECT 
    REGION_NAME,
    COUNT(DISTINCT CN.CUSTOMER_ID) AS NUMBER_OF_CUSTOMERS
FROM REGIONS AS RE
JOIN CUSTOMER_NODES AS CN ON RE.REGION_ID = CN.REGION_ID
JOIN CUSTOMER_TRANSACTIONS AS CT ON CN.CUSTOMER_ID = CT.CUSTOMER_ID
GROUP BY REGION_NAME;

-- 4. How many days on average are customers reallocated to a different node?

WITH DAY AS (
SELECT
    CN.CUSTOMER_ID,
    NODE_ID,
    SUM(DATEDIFF('day',START_DATE,END_DATE)) AS DAYS
FROM REGIONS AS RE
JOIN CUSTOMER_NODES AS CN ON RE.REGION_ID = CN.REGION_ID
JOIN CUSTOMER_TRANSACTIONS AS CT ON CN.CUSTOMER_ID = CT.CUSTOMER_ID
WHERE YEAR(END_DATE) != '9999' 
GROUP BY CN.CUSTOMER_ID,NODE_ID
)
SELECT
    AVG(DAYS) AS AVG_DAYS
FROM
    DAY;

-- 5. What is the median, 80th and 95th percentile for this same reallocation days metric for each region?

WITH DAY AS (
SELECT
    CN.CUSTOMER_ID,
    REGION_NAME,
    NODE_ID,
    SUM(DATEDIFF('day',START_DATE,END_DATE)) AS DAYS
FROM REGIONS AS RE
JOIN CUSTOMER_NODES AS CN ON RE.REGION_ID = CN.REGION_ID
JOIN CUSTOMER_TRANSACTIONS AS CT ON CN.CUSTOMER_ID = CT.CUSTOMER_ID
WHERE YEAR(END_DATE) != '9999' 
GROUP BY CN.CUSTOMER_ID,NODE_ID, REGION_NAME
),
ORDER AS (
SELECT
    DAYS,
    REGION_NAME,
    ROW_NUMBER() OVER (PARTITION BY REGION_NAME ORDER BY DAYS) AS RN;


-- INCOMPLETE
