-- 1. What are the standard ingredients for each pizza?

SELECT 
    PT.TOPPING_NAME,
    COUNT(DISTINCT pizza_id) as APPEARS_X_TIMES
FROM pizza_recipes as PR
LEFT JOIN LATERAL SPLIT_TO_TABLE(toppings,', ') as TOP
INNER JOIN PIZZA_TOPPINGS AS PT ON PT.TOPPING_ID = TOP.VALUE
GROUP BY PT.TOPPING_NAME
HAVING
    COUNT (DISTINCT PIZZA_ID) > 1;

-- 2. What was the most commonly added extra?

SELECT 
    PT.TOPPING_NAME,
    PT.TOPPING_ID,
    COUNT(CO.pizza_id) AS APPEARS_X_TIMES
FROM
    CUSTOMER_ORDERS AS CO
JOIN LATERAL SPLIT_TO_TABLE(EXTRAS, ', ') AS EX
JOIN PIZZA_TOPPINGS AS PT ON PT.TOPPING_ID = TRY_CAST(NULLIF(EX.VALUE, '') AS INT)
WHERE (EX.VALUE IS NOT NULL AND EX.VALUE != 'null' AND TRY_CAST(NULLIF(EX.VALUE, '') AS INT) IS NOT NULL)
GROUP BY PT.TOPPING_NAME, PT.TOPPING_ID;


-- 3. What was the most common exclusion?

SELECT 
    PT.TOPPING_NAME,
    PT.TOPPING_ID,
    COUNT(CO.pizza_id) AS APPEARS_X_TIMES
FROM
    CUSTOMER_ORDERS AS CO
JOIN LATERAL SPLIT_TO_TABLE(EXCLUSIONS, ', ') AS EX
JOIN PIZZA_TOPPINGS AS PT ON PT.TOPPING_ID = TRY_CAST(NULLIF(EX.VALUE, '') AS INT)
WHERE (EX.VALUE IS NOT NULL AND EX.VALUE != 'null' AND TRY_CAST(NULLIF(EX.VALUE, '') AS INT) IS NOT NULL)
GROUP BY PT.TOPPING_NAME, PT.TOPPING_ID;

-- Incomplete
