// https://preppindata.blogspot.com/2021/01/2021-week-2.html

// Output 1
SELECT
    REGEXP_REPLACE(MODEL, '[^a-zA-Z]','') AS BRAND,
    BIKE_TYPE,
    SUM(QUANTITY) AS QUANTITY_SOLD,
    SUM(VALUE_PER_BIKE * QUANTITY) AS ORDER_VALUE,
    AVG(VALUE_PER_BIKE) AS AVG_VALUE_SOLD
FROM PD2021_WK02_BIKE_SALES
GROUP BY BRAND, BIKE_TYPE;

// Output 2
SELECT
     REGEXP_REPLACE(MODEL, '[^a-zA-Z]','') AS BRAND,
     STORE,
     SUM(VALUE_PER_BIKE * QUANTITY) AS ORDER_VALUE,
     SUM(QUANTITY) AS QUANTITY_SOLD,
     AVG(DATEDIFF('day',TO_DATE(ORDER_DATE,'DD/MM/YYYY'),TO_DATE(SHIPPING_DATE,'DD/MM/YYYY'))) AS AVG_DAYS_TO_SHIP
FROM PD2021_WK02_BIKE_SALES
GROUP BY BRAND, STORE;
