// https://preppindata.blogspot.com/2023/01/2023-week-3-targets-for-dsb.html

WITH PT AS (
  SELECT 
        CAST(TRIM(REGEXP_REPLACE(QUARTER, '[^0-9]', '')) AS INT) AS QUARTERS, 
        QUARTERLY_TARGETS,
        ONLINE_OR_IN_PERSON
  FROM 
    pd2023_wk03_targets
  UNPIVOT(
        QUARTERLY_TARGETS FOR QUARTER IN (Q1,Q2,Q3,Q4)
    )
),

WK AS 
(
SELECT 
      CASE
        WHEN ONLINE_OR_IN_PERSON = 1 THEN 'Online'
        WHEN online_or_in_person = 2 THEN 'In-Person'
        END AS ONLINE_OR_IN_PERSON,
    CAST(QUARTER(TO_DATE(TRIM(SPLIT_PART(TRANSACTION_DATE,' ',1)),'DD/MM/YYYY')) AS INT) AS QUARTER,
    SUM(VALUE) AS TOTAL_VALUES
FROM 
  PD2023_WK01
WHERE 
  CONTAINS(TRANSACTION_CODE,'DSB')
GROUP BY 
  ONLINE_OR_IN_PERSON, QUARTER
)

SELECT
      WK.ONLINE_OR_IN_PERSON AS ONLINE_OR_IN_PERSON,
      QUARTER AS QUARTER,
      TOTAL_VALUES,
      QUARTERLY_TARGETS,
      TOTAL_VALUES - QUARTERLY_TARGETS AS TARGET_VARIANCE
FROM 
  PT
JOIN 
  WK ON PT.QUARTERS = WK.QUARTER AND PT.ONLINE_OR_IN_PERSON = WK.ONLINE_OR_IN_PERSON;
