//Bullet Points 1-4
WITH 
MAD AS (
    SELECT 
        CUSTOMER_ID, 
        SPLIT_PART(MOBILE_APP_SUBJECT,'___',2) AS MA_CATEGORY, 
        RATING AS MOBILE_APP_RATING,
    FROM PD2023_WK06_DSB_CUSTOMER_SURVEY
    UNPIVOT(
        RATING FOR MOBILE_APP_SUBJECT IN (
            MOBILE_APP___EASE_OF_USE, 
            MOBILE_APP___EASE_OF_ACCESS, 
            MOBILE_APP___NAVIGATION, 
            MOBILE_APP___LIKELIHOOD_TO_RECOMMEND
        )
    ) AS MAD
), 
OID AS (
    SELECT 
        CUSTOMER_ID, 
        SPLIT_PART(ONLINE_INTERFACE_SUBJECT,'___',2) AS OI_CATEGORY, 
        RATINGS AS ONLINE_INTERFACE_RATING,
    FROM PD2023_WK06_DSB_CUSTOMER_SURVEY
    UNPIVOT(
        RATINGS FOR ONLINE_INTERFACE_SUBJECT IN (
            ONLINE_INTERFACE___EASE_OF_USE, 
            ONLINE_INTERFACE___EASE_OF_ACCESS, 
            ONLINE_INTERFACE___NAVIGATION, 
            ONLINE_INTERFACE___LIKELIHOOD_TO_RECOMMEND 
        )
    ) AS OID
)

SELECT 
COALESCE(MAD.CUSTOMER_ID, OID.CUSTOMER_ID) AS CUSTOMER_ID,
MA_CATEGORY, 
MOBILE_APP_RATING,
OI_CATEGORY,
ONLINE_INTERFACE_RATING,
FROM MAD
JOIN OID ON MAD.CUSTOMER_ID = OID.CUSTOMER_ID AND MAD.MA_CATEGORY = OID.OI_CATEGORY
ORDER BY CUSTOMER_ID;

// Bullet Points 5-9

WITH 
MAD AS (
    SELECT 
        CUSTOMER_ID, 
        SPLIT_PART(MOBILE_APP_SUBJECT,'___',2) AS MA_CATEGORY, 
        RATING AS MOBILE_APP_RATING,
    FROM PD2023_WK06_DSB_CUSTOMER_SURVEY
    UNPIVOT(
        RATING FOR MOBILE_APP_SUBJECT IN (
            MOBILE_APP___EASE_OF_USE, 
            MOBILE_APP___EASE_OF_ACCESS, 
            MOBILE_APP___NAVIGATION, 
            MOBILE_APP___LIKELIHOOD_TO_RECOMMEND
        )
    ) AS MAD
), 
OID AS (
    SELECT 
        CUSTOMER_ID, 
        SPLIT_PART(ONLINE_INTERFACE_SUBJECT,'___',2) AS OI_CATEGORY, 
        RATINGS AS ONLINE_INTERFACE_RATING,
    FROM PD2023_WK06_DSB_CUSTOMER_SURVEY
    UNPIVOT(
        RATINGS FOR ONLINE_INTERFACE_SUBJECT IN (
            ONLINE_INTERFACE___EASE_OF_USE, 
            ONLINE_INTERFACE___EASE_OF_ACCESS, 
            ONLINE_INTERFACE___NAVIGATION, 
            ONLINE_INTERFACE___LIKELIHOOD_TO_RECOMMEND 
        )
    ) AS OID
),
    MIXED AS (
    SELECT
        COALESCE(MAD.CUSTOMER_ID, OID.CUSTOMER_ID) AS CUSTOMER_ID,
        AVG(MOBILE_APP_RATING) AS AVG_MA_RATING,
        AVG(ONLINE_INTERFACE_RATING) AS AVG_OI_RATING,
        AVG(MOBILE_APP_RATING) - AVG(ONLINE_INTERFACE_RATING) AS DIFFERENCE
    FROM MAD
    JOIN OID ON MAD.CUSTOMER_ID = OID.CUSTOMER_ID AND MAD.MA_CATEGORY = OID.OI_CATEGORY
    GROUP BY COALESCE(MAD.CUSTOMER_ID, OID.CUSTOMER_ID)
)

    SELECT 
      CASE
         WHEN DIFFERENCE >= 2 THEN 'MOBILE APP SUPERFAN'
         WHEN DIFFERENCE >= 1 THEN 'MOBILE APP FAN'
         WHEN DIFFERENCE < 1 AND DIFFERENCE > -1 THEN 'NEUTRAL'
         WHEN DIFFERENCE <= -1 AND DIFFERENCE > -2 THEN 'ONLINE INTERFACE FAN'
         WHEN DIFFERENCE <= -2 THEN 'ONLINE INTERFACE SUPERFAN'
    END AS PREFERENCE,
        RATIO_TO_REPORT(COUNT(PREFERENCE)) OVER () AS PERCENT_OF_TOTAL
FROM MIXED
GROUP BY 
     CASE
         WHEN DIFFERENCE >= 2 THEN 'MOBILE APP SUPERFAN'
         WHEN DIFFERENCE >= 1 THEN 'MOBILE APP FAN'
         WHEN DIFFERENCE < 1 AND DIFFERENCE > -1 THEN 'NEUTRAL'
         WHEN DIFFERENCE <= -1 AND DIFFERENCE > -2 THEN 'ONLINE INTERFACE FAN'
         WHEN DIFFERENCE <= -2 THEN 'ONLINE INTERFACE SUPERFAN'
    END
ORDER BY PREFERENCE;
