// https://preppindata.blogspot.com/2023/01/2023-week-1-data-source-bank.html

//Output 1
SELECT 
  SPLIT_PART(transaction_code,'-',1) AS BANK,
  SUM(VALUE) AS TOTAL_VALUE,
FROM PD2023_WK01
GROUP BY BANK;

//Output 2
SELECT 
  SPLIT_PART(transaction_code,'-',1) AS BANK,
  CASE
    WHEN ONLINE_OR_IN_PERSON = 1 THEN 'Online'
    WHEN ONLINE_OR_IN_PERSON = 2 THEN 'In-Person'
    END AS ONLINE_OR_IN_PERSON,
  DAYNAME(TO_DATE(TRIM(SPLIT_PART(TRANSACTION_DATE,' ',1)),'DD/MM/YYYY')) AS DAY_OF_WEEK,
  SUM(VALUE) AS TOTAL_VALUE
FROM PD2023_WK01
GROUP BY BANK, DAY_OF_WEEK, ONLINE_OR_IN_PERSON;

//Output 3
SELECT 
  SPLIT_PART(transaction_code,'-',1) AS BANK,
  CUSTOMER_CODE,
  SUM(VALUE) AS TOTAL_VALUE
FROM PD2023_WK01
GROUP BY BANK, CUSTOMER_CODE;
