// https://community.alteryx.com/t5/Weekly-Challenges/Challenge-287-Find-My-Pet-US/td-p/827204

                                                 //CHALLENGE 287 PT1
SELECT 
    OWNER_FIRST_NAME,
    OWNER_LAST_NAME,
    OI.CITY,
    OI.STATE_NAME, 
    CAST(REGEXP_REPLACE(new_pet_rewards, '[^A-Za-z0-9\s]', '') AS NUMBER) AS NEW_PET_REWARD,
    ST_DISTANCE(ST_MAKEPOINT(PI.long,PI.lat),ST_MAKEPOINT(OI.long,OI.lat)) / 1609 AS DISTANCE_MILES,
FROM AYX287_ANIMAL_REWARDS AS AR
JOIN AYX287_PET_INFO AS PI ON AR.ANIMAL_ID = PI.ANIMAL_ID
JOIN AYX287_OWNER_INFO AS OI ON AR.ANIMAL_ID = OI.ANIMAL_ID
WHERE NEW_PET_REWARD >= 2700 AND DISTANCE_MILES <= 500;
                                                //CHALLENGE 287 PT2
SELECT 
    OWNER_FIRST_NAME,
    OWNER_LAST_NAME,
    OI.CITY,
    OI.STATE_NAME, 
    CAST(REGEXP_REPLACE(new_pet_rewards, '[^A-Za-z0-9\s]', '') AS NUMBER) AS NEW_PET_REWARD,
    ST_DISTANCE(ST_MAKEPOINT(PI.long,PI.lat),ST_MAKEPOINT(OI.long,OI.lat)) / 1609 AS DISTANCE_MILES,
    NEW_PET_REWARD / DISTANCE_MILES AS REWARD_PER_MILE
FROM AYX287_ANIMAL_REWARDS AS AR
JOIN AYX287_PET_INFO AS PI ON AR.ANIMAL_ID = PI.ANIMAL_ID
JOIN AYX287_OWNER_INFO AS OI ON AR.ANIMAL_ID = OI.ANIMAL_ID
ORDER BY REWARD_PER_MILE DESC
LIMIT 1;
