// https://community.alteryx.com/t5/Weekly-Challenges/Challenge-363-Coffee-or-Tea-That-s-the-question/td-p/1099462

                                                // CHALLENGE 363 Q1
SELECT 
    STATE,
    SUM(SALES) AS TOTAL_SALES
FROM AYX363_COFFEE_TEA_SALES
WHERE PRODUCT_LINE = 'Coffee' AND TYPE ='Regular'
GROUP BY STATE
ORDER BY TOTAL_SALES DESC
LIMIT 1;
                                                //CHALLENGE 363 Q2
SELECT 
    STATE,
    SUM(SALES) AS TOTAL_SALES
FROM AYX363_COFFEE_TEA_SALES
WHERE PRODUCT_LINE = 'Coffee' AND TYPE ='Decaf'
GROUP BY STATE
ORDER BY TOTAL_SALES DESC
LIMIT 1;
                                                //CHALLENGE 363 Q3
SELECT 
    PRODUCT_TYPE,
    SUM(SALES) AS TOTAL_SALES
FROM AYX363_COFFEE_TEA_SALES
WHERE PRODUCT_LINE = 'Coffee' 
GROUP BY PRODUCT_TYPE
ORDER BY TOTAL_SALES DESC
LIMIT 1;
                                                //CHALLENGE 363 Q4
SELECT 
    STATE,
    SUM(SALES) AS TOTAL_SALES
FROM AYX363_COFFEE_TEA_SALES
WHERE PRODUCT_LINE = 'Tea' AND TYPE ='Regular'
GROUP BY STATE
ORDER BY TOTAL_SALES DESC
LIMIT 1;
                                                //CHALLENGE 363 Q5
SELECT 
    STATE,
    SUM(SALES) AS TOTAL_SALES
FROM AYX363_COFFEE_TEA_SALES
WHERE PRODUCT_LINE = 'Tea' AND TYPE ='Decaf'
GROUP BY STATE
ORDER BY TOTAL_SALES DESC
LIMIT 1;
                                                //CHALLENGE 363 Q6
SELECT 
    PRODUCT_TYPE,
    SUM(SALES) AS TOTAL_SALES
FROM AYX363_COFFEE_TEA_SALES
WHERE PRODUCT_LINE = 'Tea' 
GROUP BY PRODUCT_TYPE
ORDER BY TOTAL_SALES DESC
LIMIT 1;
