// https://community.alteryx.com/t5/Weekly-Challenges/Challenge-283-The-Summer-Paralympic-Games-2020/td-p/808416

                                                //CHALLENGE 283 Q1
SELECT 
    NOC AS COUNTRY,
    COUNT(RECORDID) AS ATHLETE_COUNT
FROM AYX283_ATHLETES
GROUP BY COUNTRY;
                                                //CHALLENGE 283 Q2
SELECT 
    NOC AS COUNTRY,
    COUNT(RECORDID) AS ATHLETE_COUNT
FROM AYX283_ATHLETES
GROUP BY COUNTRY
ORDER BY ATHLETE_COUNT DESC
LIMIT 5;
                                                //CHALLENGE 283 Q3
SELECT 
    NOC AS COUNTRY,
    COUNT(RECORDID) AS ATHLETE_COUNT
FROM AYX283_ATHLETES
GROUP BY COUNTRY
ORDER BY ATHLETE_COUNT ASC, COUNTRY ASC 
LIMIT 5;
                                                //CHALLENGE 283 Q4
SELECT 
    NOC AS COUNTRY,
    DISCIPLINE,
    COUNT(RECORDID) AS ATHLETE_COUNT
FROM AYX283_ATHLETES
GROUP BY COUNTRY, DISCIPLINE
ORDER BY COUNTRY ASC, DISCIPLINE ASC;
